#!/bin/bash

root="$(git rev-parse --show-toplevel)"
cd "$root" || exit 1

if [[ ! -r go.mod ]]; then
    exit 0
fi

mod="$(grep -E "^replace\s+.+\s{1}=>\s{1}.+$" go.mod 2>/dev/null)"
if [[ -z "$mod" ]]; then
    exit 0
fi

echo "replace directive found in go.mod. Remove it before committing"
exit 1
